CREATE TABLE public.record_cover_cleanup_jobs (
	id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id UUID NOT NULL,
	record_id UUID NOT NULL,
	object_path TEXT NOT NULL UNIQUE,
	created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
	attempt_count INTEGER NOT NULL DEFAULT 0,
	last_attempted_at TIMESTAMPTZ,
	CONSTRAINT record_cover_cleanup_jobs_attempt_count_check
		CHECK (attempt_count >= 0),
	CONSTRAINT record_cover_cleanup_jobs_object_path_check
		CHECK (
			object_path ~ (
				'^'
				|| user_id::TEXT
				|| '/'
				|| record_id::TEXT
				|| '/[^/]+[.]webp$'
			)
		)
);

CREATE INDEX record_cover_cleanup_jobs_user_id_id_idx
ON public.record_cover_cleanup_jobs (user_id, id);

ALTER TABLE public.record_cover_cleanup_jobs ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.record_cover_cleanup_jobs
FROM PUBLIC, anon, authenticated, service_role;
GRANT SELECT, INSERT, UPDATE, DELETE
ON TABLE public.record_cover_cleanup_jobs
TO service_role;

-- The cleanup worker rechecks live references immediately before Storage
-- deletion. A prior least-privilege migration removed service_role's inherited
-- table access, so grant only the two record columns needed for that check.
GRANT SELECT (user_id, cover_storage_path)
ON TABLE public.records
TO service_role;

REVOKE ALL ON SEQUENCE public.record_cover_cleanup_jobs_id_seq
FROM PUBLIC, anon, authenticated, service_role;
GRANT USAGE, SELECT
ON SEQUENCE public.record_cover_cleanup_jobs_id_seq
TO service_role;

CREATE FUNCTION public.queue_obsolete_record_cover()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
	obsolete_path TEXT;
	expected_prefix TEXT;
	file_name TEXT;
BEGIN
	IF TG_OP = 'UPDATE' THEN
		IF OLD.cover_storage_path IS NOT DISTINCT FROM NEW.cover_storage_path THEN
			RETURN NEW;
		END IF;
		obsolete_path := OLD.cover_storage_path;
	ELSE
		obsolete_path := OLD.cover_storage_path;
	END IF;

	IF obsolete_path IS NULL THEN
		RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
	END IF;

	expected_prefix := OLD.user_id::TEXT || '/' || OLD.id::TEXT || '/';
	IF left(obsolete_path, length(expected_prefix)) <> expected_prefix THEN
		RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
	END IF;

	file_name := substring(obsolete_path FROM length(expected_prefix) + 1);
	IF
		length(file_name) <= length('.webp')
		OR position('/' IN file_name) > 0
		OR right(file_name, length('.webp')) <> '.webp'
	THEN
		RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
	END IF;

	INSERT INTO public.record_cover_cleanup_jobs (
		user_id,
		record_id,
		object_path
	)
	VALUES (
		OLD.user_id,
		OLD.id,
		obsolete_path
	)
	ON CONFLICT (object_path) DO NOTHING;

	RETURN CASE WHEN TG_OP = 'DELETE' THEN OLD ELSE NEW END;
END;
$$;

REVOKE ALL ON FUNCTION public.queue_obsolete_record_cover()
FROM PUBLIC, anon, authenticated, service_role;

CREATE TRIGGER records_queue_obsolete_cover_trigger
AFTER UPDATE OF cover_storage_path OR DELETE ON public.records
FOR EACH ROW
EXECUTE FUNCTION public.queue_obsolete_record_cover();
